version: '3'
services:
  wordpress:
    build:
      context: ./docker-settings/wordpress
      args:
        - BUILD_ENV=production
    volumes:
      - ./site:/var/www/html/wp-content
    env_file:
      - .env
      - .env.prod
    ports:
      - "80:80"
      - "443:443"
    restart: always
    links:
      - db:mysql
  db:
    image: mariadb:10.3
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - 3306:3306
    env_file:
      - .env
      - .env.prod
    restart: always